workflows:
  build-android:
    name: Build APK for Android
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      android_signing:
        - vivop_key
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - tu-email@ejemplo.com
